apiVersion: v1
kind: Pod
metadata:
    name: amandine-pod-webapp
    labels:
        app: webapp
spec:
    containers:
        - name: webapp
          image: kodekloud/webapp-color
          ports:
            - containerPort: 8080
              hostPort: 8080
          env:
            - name: APP_COLOR
              value: red
  